logging:
  level:
    web: debug
    
server:
  port: 9999
  servlet:
    session:
      cookie:
        same-site: "none"
      tracking-modes:
        - URL
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER